name: Push-to-EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ec2-3-87-224-1.compute-1.amazonaws.com
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            # Set working directory
            cd ~
            
            # Clone the repo if it doesn't exist
            if [ ! -d "cicd" ]; then
              git clone https://github.com/Sanjeev12357/cicd.git
            fi

            # Navigate and pull latest changes
            cd cicd
            git pull origin main

            # Install dependencies and build
            npm install
            npm run build
            
            npm run start

